name: flutter_appkit
description: Production-ready runtime and infrastructure support for Flutter apps â€” error handling, logging, locale, context, Riverpod, and more.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.0
homepage: https://github.com/piyuo/flutter-appkit/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sentry_flutter: ^9.11.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  flutter_riverpod: ^3.2.0
  talker: ^5.1.13
  talker_flutter: ^5.1.13
  talker_riverpod_logger: ^5.1.13
  flutter_dotenv: ^6.0.0
  universal_io: ^2.2.2
dev_dependencies:
  sentry_dart_plugin: ^3.1.1
  flutter_test:
    sdk: flutter
  mockito: ^5.6.3
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  analyzer: ^8.4.0
dependency_overrides:
  analyzer: ^10.0.1
  #meta: ^1.11.0 #cause flutter_test blocked

# The following section is specific to Flutter.
flutter:
    generate: true
    uses-material-design: true
    # To add assets to your package, add an assets section, like this:
    assets:
    - .env.test
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: piyuo